import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { DataTable } from "@/components/datatable/data-table";
import { bugReportColumns } from "@/components/datatable/columns/bugs";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { useState } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useRouter } from "next/router";

export default function Home() {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState<0 | 1 | 2>(0);
  const router = useRouter();
  const createReport = api.bug.create.useMutation();
  return (
    <>
      <Head>
        <title>BugTracker - Create</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="w-full p-3 text-center text-2xl text-white">
          Create a Bug Report
        </div>

        <div className="flex w-full flex-col items-center justify-center gap-2">
          <div className="w-7/12">
            <Label className="text-white">Name</Label>
            <Input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="name"
            />
          </div>

          <div className="w-7/12">
            <Label className="text-white">Description</Label>
            <Input
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="description"
            />
          </div>

          <div className="w-7/12">
            <Label className="text-white">Category</Label>
            <Input
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              placeholder="category"
            />
          </div>

          <div className="w-7/12">
            <Label className="text-white">Status</Label>
            <Select
              required
              value={`${status}`}
              onValueChange={(e) => {
                setStatus(Number.parseInt(e) as 0 | 1 | 2);
              }}
            >
              <SelectTrigger className="relative h-10 rounded-md border border-[#E2E8F0]">
                <SelectValue placeholder="Select a status..." />
                {/* Displays a dropdown arrow. */}
                <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2">
                  <svg
                    className="h-4 w-4 fill-current text-gray-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                  >
                    <path d="M10 12l-6-6-1.414 1.414L10 14.828l7.414-7.414L16 6z"></path>
                  </svg>
                </div>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="0">Open</SelectItem>
                <SelectItem value="1">In Progress</SelectItem>
                <SelectItem value="2">Closed</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Link href="/create">
            <Button
              className="mt-4"
              onClick={() =>
                createReport.mutate(
                  { name, description, category, fixed: status },
                  {
                    onSuccess: () => {
                      router.push("/");
                    },
                  },
                )
              }
            >
              Create Bug Report
            </Button>
          </Link>
        </div>
      </main>
    </>
  );
}
